#!/usr/bin/env python3
"""
Search Agent - Executes web searches and formats results for the search-web skill.

This script is designed to be called by the main agent or run standalone
to perform focused web searches and output structured markdown.

Usage:
    python3 search_agent.py "search query" --output /path/to/results.md
    python3 search_agent.py "PowerShell vs Bash benchmark" --round 1 --cluster "comparison"
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path


def create_output_dir(base_path: str, task_name: str) -> Path:
    """Create structured output directory for search results."""
    today = datetime.now().strftime("%Y-%m-%d")
    output_dir = Path(base_path) / f"search-web/{today}/{task_name}"
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def format_result(query: str, results: list, round_num: int, cluster_name: str) -> str:
    """Format search results as markdown."""
    timestamp = datetime.now().isoformat()

    md = f"""## Search Round {round_num} - {cluster_name}

**Query:** `{query}`
**Time:** {timestamp}

### Results

"""

    for i, result in enumerate(results, 1):
        relevance = result.get('relevance', 'N/A')
        title = result.get('title', 'Untitled')
        url = result.get('url', 'N/A')
        findings = result.get('findings', [])
        quotes = result.get('quotes', [])

        md += f"""#### Result {i}: {title}
- **URL:** {url}
- **Relevance:** {relevance}/5
- **Key Findings:
"""
        for finding in findings:
            md += f"  - {finding}\n"

        if quotes:
            md += "- **Quotes:**\n"
            for quote in quotes:
                md += f"  > {quote}\n"

        md += "\n"

    return md


def create_master_log_header(goal: str, query_clusters: list) -> str:
    """Create the header for the master log file."""
    today = datetime.now().strftime("%Y-%m-%d")
    timestamp = datetime.now().isoformat()

    clusters_md = "\n".join([f"{i+1}. {cluster}" for i, cluster in enumerate(query_clusters)])

    return f"""# Search Session Log

**Date:** {today}
**Started:** {timestamp}

## Research Goal

{goal}

## Query Clusters

{clusters_md}

---

"""


def create_summary_template() -> str:
    """Create the summary section template."""
    return """

## Summary

### Key Findings

| Finding | Source | Confidence |
|---------|--------|------------|
| | | |

### Evidence Assessment

- **Supports hypothesis:**
  -
- **Contradicts hypothesis:**
  -
- **Inconclusive:**
  -

### Next Round Queries

1.
2.

---

*Log generated by search-web skill*
"""


def main():
    parser = argparse.ArgumentParser(
        description="Execute web search and format results for search-web skill"
    )
    parser.add_argument("query", help="Search query string")
    parser.add_argument(
        "--output", "-o",
        default="/tmp",
        help="Base output directory (default: /tmp)"
    )
    parser.add_argument(
        "--task", "-t",
        default="search-task",
        help="Task name for directory organization"
    )
    parser.add_argument(
        "--round", "-r",
        type=int,
        default=1,
        help="Search round number"
    )
    parser.add_argument(
        "--cluster", "-c",
        default="general",
        help="Query cluster name"
    )
    parser.add_argument(
        "--goal",
        help="Research goal (for master log header)"
    )
    parser.add_argument(
        "--init",
        action="store_true",
        help="Initialize master log with header only"
    )

    args = parser.parse_args()

    # Create output directory
    output_dir = create_output_dir(args.output, args.task)
    master_log = output_dir / "master-log.md"

    if args.init and args.goal:
        # Initialize master log with header
        query_clusters = [args.cluster] if args.cluster != "general" else []
        header = create_master_log_header(args.goal, query_clusters)
        with open(master_log, 'w', encoding='utf-8') as f:
            f.write(header)
            f.write(create_summary_template())
        print(f"Initialized master log: {master_log}")
        return

    # This script is designed to be a template/reference
    # Actual search execution is handled by the main agent using WebSearch/WebFetch tools
    # This script provides the structure for output formatting

    print(f"Search Agent initialized")
    print(f"Output directory: {output_dir}")
    print(f"Master log: {master_log}")
    print(f"Query: {args.query}")
    print(f"Round: {args.round}")
    print(f"Cluster: {args.cluster}")
    print("\nNote: This script provides structure. Actual searches should use")
    print("the WebSearch/WebFetch tools from the main agent or sub-agent.")


if __name__ == "__main__":
    main()
